# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - typecheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/Zillaforge/cloud-sdk

issues:
  exclude-rules:
    - path: specs/
      linters:
        - typecheck
        - errcheck
        - gosimple
        - govet
    - path: _test\.go
      linters:
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
