@PROTOCOL = {{$dotenv API_PROTOCOL}}
@HOST = {{$dotenv API_HOST}}
@PROJECT = {{$dotenv PROJECT_ID}}
@TOKEN = {{$dotenv API_TOKEN}}
@SERVICE = vrm
@BASE_URL = {{PROTOCOL}}://{{HOST}}/{{SERVICE}}/api/v1/project/{{PROJECT}}
@VPS_BASE_URL={{PROTOCOL}}://{{HOST}}/vps/api/v1/project/{{PROJECT}}
@IMAGE_SOURCE={{$dotenv IMAGE_SOURCE}}


### List Server
# @name ServerList
GET {{VPS_BASE_URL}}/servers HTTP/1.1
content-type: application/json
Authorization: Bearer {{TOKEN}}

@targetServerId={{ServerList.response.body.$.servers[0].id}}


######## Repository  API ###########

### Create Repository
# @name RepoCreate
POST {{BASE_URL}}/repository HTTP/1.1
content-type: application/json
Authorization: Bearer {{TOKEN}}

{
    "name": "user_repo",
    "operatingSystem": "linux"
}

@testRepositoryId={{RepoCreate.response.body.$.id}}


### List Repositories
# @name RepoList
GET {{BASE_URL}}/repositories HTTP/1.1
content-type: application/json
Authorization: Bearer {{TOKEN}}


### Get Repoistory
# @name RepoGet
GET {{BASE_URL}}/repository/{{testRepositoryId}}
content-type: application/json
Authorization: Bearer {{TOKEN}}


### Update repository
# @name RepoUpdate
PUT {{BASE_URL}}/repository/{{testRepositoryId}}
content-type: application/json
Authorization: Bearer {{TOKEN}}

{
    "description": "new_description1"
}


### Delete Repository
# @name RepoDelete
DELETE {{BASE_URL}}/repository/{{testRepositoryId}}
content-type: application/json
Authorization: Bearer {{TOKEN}}


### Upload from CS
# @name RepoUpload
POST {{BASE_URL}}/upload
content-type: application/json
Authorization: Bearer {{TOKEN}}

# input I: From CS to a new Repoistory:Tag
{
    "name":"new_repo",
    "version":"new_tag",
    "type":"common",
    "diskFormat":"qcow2",
    "containerFormat":"bare",
    "operatingSystem":"linux",
    "description":"",
    "filepath": "dss-public://{{IMAGE_SOURCE}}"
}

# Input II: From CS to a existing Repoistory:Tag
# {   
#     "repositoryId": "{{testRepositoryId}}",
#     "version":"new_tag",
#     "type":"common",
#     "diskFormat":"qcow2",
#     "containerFormat":"bare",
#     "filepath": "dss-public://{{IMAGE_SOURCE}}"
# }

# Input III:  From CS to a existing Tag
# {
#     "tagId": "",
#     "filepath": "dss-public://{{IMAGE_SOURCE}}"
# }

### Take Snapshot from a server become Tag
# @name SnapshotTake
POST {{BASE_URL}}/server/{{targetServerId}}/snapshot HTTP/1.1
content-type: application/json
Authorization: Bearer {{TOKEN}}


{   
    "name": "newRepositoryName",
    "operatingSystem":"linux",
    "version":"aa",
    "description":""
}

# {
#   "repositoryId": "{{testRepositoryId}}",
#   "version": "0"
# }

######## Tag Sub-Resource API ###########

### Create Tag
# @name TagCreate
POST {{BASE_URL}}/repository/{{testRepositoryId}}/tag HTTP/1.1
content-type: application/json
Authorization: Bearer {{TOKEN}}

{
    "name": "test-v1-tag",
    "type": "common",
    "diskFormat": "raw",
    "containerFormat": "bare"
}



### List Tag (only personal)
# @name TagListPersonal
GET {{BASE_URL}}/repository/{{testRepositoryId}}/tags
content-type: application/json
Authorization: Bearer {{TOKEN}}