@PROTOCOL = {{$dotenv API_PROTOCOL}}
@HOST = {{$dotenv API_HOST}}
@PROJECT = {{$dotenv PROJECT_ID}}
@TOKEN = {{$dotenv API_TOKEN}}
@SERVICE = vrm
@BASE_URL = {{PROTOCOL}}://{{HOST}}/{{SERVICE}}/api/v1/project/{{PROJECT}}


### List Tags
# @name TagsList
GET {{BASE_URL}}/tags HTTP/1.1
content-type: application/json
Authorization: Bearer {{TOKEN}}
